//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinFS.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoinFS.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to acquire access to the X-Plane aircraft. This is usually because another plugin has already been granted access. Try disabling the other plugin to give JoinFS access. ähnelt.
        /// </summary>
        internal static string AcquiredWarning {
            get {
                return ResourceManager.GetString("AcquiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to inject all aircraft. You should add more AI Aircraft to the Flight Configuration menu in X-Plane. ähnelt.
        /// </summary>
        internal static string AircraftWarning {
            get {
                return ResourceManager.GetString("AircraftWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Airliner ähnelt.
        /// </summary>
        internal static string Airliner {
            get {
                return ResourceManager.GetString("Airliner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import your JoinFS settings from v3.1.6? ähnelt.
        /// </summary>
        internal static string AskImport {
            get {
                return ResourceManager.GetString("AskImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SimConnect is required for Microsoft Flight Simulator, Prepar3D and FSX. Do you wish to download it? ähnelt.
        /// </summary>
        internal static string AskSimConnect {
            get {
                return ResourceManager.GetString("AskSimConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must first start a simulator before assigning variables. ähnelt.
        /// </summary>
        internal static string AssignVariablesWarning {
            get {
                return ResourceManager.GetString("AssignVariablesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ATC Mode is enabled. This allows aircraft to be visible on radar, but has an adverse effect on the smooth movement of aircraft. ähnelt.
        /// </summary>
        internal static string AtcModeEnabled {
            get {
                return ResourceManager.GetString("AtcModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With ATC mode enabled, network aircraft will be visible on the default radar. However, some aircraft may act in a strange manner while ATC mode is enabled. ähnelt.
        /// </summary>
        internal static string AtcWarning {
            get {
                return ResourceManager.GetString("AtcWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patreon ähnelt.
        /// </summary>
        internal static string BecomeAPatron {
            get {
                return ResourceManager.GetString("BecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bomber ähnelt.
        /// </summary>
        internal static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy Me A Coffee ähnelt.
        /// </summary>
        internal static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the JoinFS communications system. This area shows incoming messages, hub information and event notifications. On the left, select the channels to receive and transmit. Right-click to change colours. Type a message in the box below then click &apos;Send&apos; or press the enter key. Type &apos;.help&apos; for commands. ähnelt.
        /// </summary>
        internal static string CommsWelcome {
            get {
                return ResourceManager.GetString("CommsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Flight Plan... ähnelt.
        /// </summary>
        internal static string CopyFlightPlan {
            get {
                return ResourceManager.GetString("CopyFlightPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donate ähnelt.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to close JoinFS and download the new version? ähnelt.
        /// </summary>
        internal static string DownloadNew {
            get {
                return ResourceManager.GetString("DownloadNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must first start a simulator before editing substitutions. ähnelt.
        /// </summary>
        internal static string EditMatchingWarning {
            get {
                return ResourceManager.GetString("EditMatchingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Model Masquerading ähnelt.
        /// </summary>
        internal static string EditModelMasquerading {
            get {
                return ResourceManager.GetString("EditModelMasquerading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Model Matching ähnelt.
        /// </summary>
        internal static string EditModelMatching {
            get {
                return ResourceManager.GetString("EditModelMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Cockpit ähnelt.
        /// </summary>
        internal static string EnterCockpit {
            get {
                return ResourceManager.GetString("EnterCockpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighter ähnelt.
        /// </summary>
        internal static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Follow ähnelt.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found ähnelt.
        /// </summary>
        internal static string FoundPrefix {
            get {
                return ResourceManager.GetString("FoundPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die model(s) ähnelt.
        /// </summary>
        internal static string FoundSuffix {
            get {
                return ResourceManager.GetString("FoundSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FourProp ähnelt.
        /// </summary>
        internal static string FourProp {
            get {
                return ResourceManager.GetString("FourProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating CSL objects may take several minutes. You may need to restart X-Plane when complete. ähnelt.
        /// </summary>
        internal static string GenerateCslWarning {
            get {
                return ResourceManager.GetString("GenerateCslWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glider ähnelt.
        /// </summary>
        internal static string Glider {
            get {
                return ResourceManager.GetString("Glider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global ähnelt.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to install the plugin for X-Plane? ähnelt.
        /// </summary>
        internal static string InstallPlugin {
            get {
                return ResourceManager.GetString("InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid email or password ähnelt.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid height adjustment ähnelt.
        /// </summary>
        internal static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid join address. Either select from the address book or use an address in a format described in the manual. ähnelt.
        /// </summary>
        internal static string InvalidJoinAddress {
            get {
                return ResourceManager.GetString("InvalidJoinAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid port number ähnelt.
        /// </summary>
        internal static string InvalidPortPrefix {
            get {
                return ResourceManager.GetString("InvalidPortPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Needs to be in the range 1-65535 ähnelt.
        /// </summary>
        internal static string InvalidPortSuffix {
            get {
                return ResourceManager.GetString("InvalidPortSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid substitution ähnelt.
        /// </summary>
        internal static string InvalidSubstitution {
            get {
                return ResourceManager.GetString("InvalidSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join ähnelt.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leave ähnelt.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to locate the X-Plane plugins folder ähnelt.
        /// </summary>
        internal static string LocatePluginFolder {
            get {
                return ResourceManager.GetString("LocatePluginFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JoinFS is already running on this system ähnelt.
        /// </summary>
        internal static string MaxInstances {
            get {
                return ResourceManager.GetString("MaxInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model list is empty for this simulator. Would you like to scan for models now? ähnelt.
        /// </summary>
        internal static string ModelListEmpty {
            get {
                return ResourceManager.GetString("ModelListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network ähnelt.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new version available. Would you like to install it? ähnelt.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New version available ähnelt.
        /// </summary>
        internal static string NewVersionStatus {
            get {
                return ResourceManager.GetString("NewVersionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The owner of the aircraft has not given permission for you to enter. ähnelt.
        /// </summary>
        internal static string NoPermissionCockpit {
            get {
                return ResourceManager.GetString("NoPermissionCockpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to find substitute model ähnelt.
        /// </summary>
        internal static string NoSubstituteModel {
            get {
                return ResourceManager.GetString("NoSubstituteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Connected ähnelt.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This recording is an old version and no longer supported with this version of JoinFS ähnelt.
        /// </summary>
        internal static string OldRecording {
            get {
                return ResourceManager.GetString("OldRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate CSL objects for installed X-Plane aircraft during a scan. ähnelt.
        /// </summary>
        internal static string Option_GenerateCsl {
            get {
                return ResourceManager.GetString("Option_GenerateCsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip CSL objects already done during a scan. ähnelt.
        /// </summary>
        internal static string Option_SkipCsl {
            get {
                return ResourceManager.GetString("Option_SkipCsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the maximum distance in nautical miles that aircraft will be injected into the simulator. ähnelt.
        /// </summary>
        internal static string Options_ActivityCircle {
            get {
                return ResourceManager.GetString("Options_ActivityCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifies the airport this ATC is controlling from. For example, &apos;EGLL&apos;. ähnelt.
        /// </summary>
        internal static string Options_Airport {
            get {
                return ResourceManager.GetString("Options_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable ATC mode. Other users will see you marked as ATC. ähnelt.
        /// </summary>
        internal static string Options_Atc {
            get {
                return ResourceManager.GetString("Options_Atc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For JoinFS-CONSOLE, run as a background task with no keyboard input. ähnelt.
        /// </summary>
        internal static string Options_Background {
            get {
                return ResourceManager.GetString("Options_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new session if hub mode is not enabled ähnelt.
        /// </summary>
        internal static string Options_Create {
            get {
                return ResourceManager.GetString("Options_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the distance in meters at which your aircraft will be positioned behind another object. Applies to follow option in the aircraft list. ähnelt.
        /// </summary>
        internal static string Options_Follow {
            get {
                return ResourceManager.GetString("Options_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join the global session immediately. ähnelt.
        /// </summary>
        internal static string Options_Global {
            get {
                return ResourceManager.GetString("Options_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show usage details. ähnelt.
        /// </summary>
        internal static string Options_Help {
            get {
                return ResourceManager.GetString("Options_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install the X-Plane plugin for JoinFS ähnelt.
        /// </summary>
        internal static string Options_InstallPlugin {
            get {
                return ResourceManager.GetString("Options_InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join a session at the specified address ähnelt.
        /// </summary>
        internal static string Options_Join {
            get {
                return ResourceManager.GetString("Options_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch JoinFS minimized on the Windows task bar. Quiet mode. ähnelt.
        /// </summary>
        internal static string Options_Minimize {
            get {
                return ResourceManager.GetString("Options_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a nickname. Others will be able to see this in the aircraft and user lists. ähnelt.
        /// </summary>
        internal static string Options_Nickname {
            get {
                return ResourceManager.GetString("Options_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run JoinFS as a background process without any windows or UI. ähnelt.
        /// </summary>
        internal static string Options_NoGui {
            get {
                return ResourceManager.GetString("Options_NoGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not connect to the simulator at launch. ähnelt.
        /// </summary>
        internal static string Options_NoSim {
            get {
                return ResourceManager.GetString("Options_NoSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open a JoinFS recorder file and play back the recording in the current session. Other users will need to enable &apos;Allow Multiple Objects&apos;. See Manual. ähnelt.
        /// </summary>
        internal static string Options_Play {
            get {
                return ResourceManager.GetString("Options_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use the specified IP port for connections to other sessions. The default port is 6112. ähnelt.
        /// </summary>
        internal static string Options_Port {
            get {
                return ResourceManager.GetString("Options_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminate all instances of JoinFS currently running on this machine. ähnelt.
        /// </summary>
        internal static string Options_Quit {
            get {
                return ResourceManager.GetString("Options_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Immediately start recording. ähnelt.
        /// </summary>
        internal static string Options_Record {
            get {
                return ResourceManager.GetString("Options_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join the previous session. ähnelt.
        /// </summary>
        internal static string Options_Rejoin {
            get {
                return ResourceManager.GetString("Options_Rejoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the simulator root folder. ähnelt.
        /// </summary>
        internal static string Options_SimFolder {
            get {
                return ResourceManager.GetString("Options_SimFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Plane plugin successfully installed ähnelt.
        /// </summary>
        internal static string PluginInstalled {
            get {
                return ResourceManager.GetString("PluginInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The recorder is empty. Choose &apos;Recorder|Record&apos; from the menu to make a recording. ähnelt.
        /// </summary>
        internal static string RecorderEmpty {
            get {
                return ResourceManager.GetString("RecorderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recorder ähnelt.
        /// </summary>
        internal static string RecorderStr {
            get {
                return ResourceManager.GetString("RecorderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tick the box to record the logs to a file before viewing. ähnelt.
        /// </summary>
        internal static string RecordLogs {
            get {
                return ResourceManager.GetString("RecordLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset all settings back to the default state? ähnelt.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotorcraft ähnelt.
        /// </summary>
        internal static string Rotorcraft {
            get {
                return ResourceManager.GetString("Rotorcraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to save your current recording? ähnelt.
        /// </summary>
        internal static string SaveCurrentRecording {
            get {
                return ResourceManager.GetString("SaveCurrentRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning is not supported with Microsoft Flight Simulator 2020. Models are automatically discovered as they appear in the simulator. ähnelt.
        /// </summary>
        internal static string Scan2020 {
            get {
                return ResourceManager.GetString("Scan2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan For Models ähnelt.
        /// </summary>
        internal static string ScanForModels {
            get {
                return ResourceManager.GetString("ScanForModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must first start the simulator before scanning for models. ähnelt.
        /// </summary>
        internal static string ScanWarning {
            get {
                return ResourceManager.GetString("ScanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G ähnelt.
        /// </summary>
        internal static string ShareAncillarySuffix {
            get {
                return ResourceManager.GetString("ShareAncillarySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die F ähnelt.
        /// </summary>
        internal static string ShareFlightSuffix {
            get {
                return ResourceManager.GetString("ShareFlightSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N ähnelt.
        /// </summary>
        internal static string ShareNavSuffix {
            get {
                return ResourceManager.GetString("ShareNavSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow shared cockpit with selected user ähnelt.
        /// </summary>
        internal static string Shortcuts_Allow {
            get {
                return ResourceManager.GetString("Shortcuts_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hand over controls to selected user ähnelt.
        /// </summary>
        internal static string Shortcuts_Controls {
            get {
                return ResourceManager.GetString("Shortcuts_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter/leave cockpit of selected aircraft ähnelt.
        /// </summary>
        internal static string Shortcuts_Enter {
            get {
                return ResourceManager.GetString("Shortcuts_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Follow selected aircraft ähnelt.
        /// </summary>
        internal static string Shortcuts_Follow {
            get {
                return ResourceManager.GetString("Shortcuts_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle the network state on/off ähnelt.
        /// </summary>
        internal static string Shortcuts_Network {
            get {
                return ResourceManager.GetString("Shortcuts_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle the simulator state on/off ähnelt.
        /// </summary>
        internal static string Shortcuts_Simulator {
            get {
                return ResourceManager.GetString("Shortcuts_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SingleProp ähnelt.
        /// </summary>
        internal static string SingleProp {
            get {
                return ResourceManager.GetString("SingleProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ähnelt.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the colour to use when something in JoinFS is active ähnelt.
        /// </summary>
        internal static string Tip_Active {
            get {
                return ResourceManager.GetString("Tip_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ICAO code for the airport you are controlling ähnelt.
        /// </summary>
        internal static string Tip_Airport {
            get {
                return ResourceManager.GetString("Tip_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep the JoinFS windows in the foreground ähnelt.
        /// </summary>
        internal static string Tip_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Tip_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Let others know that you are providing ATC coverage at an airport or region ähnelt.
        /// </summary>
        internal static string Tip_ATC {
            get {
                return ResourceManager.GetString("Tip_ATC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh all JoinFS windows every 30 seconds ähnelt.
        /// </summary>
        internal static string Tip_AutoRefresh {
            get {
                return ResourceManager.GetString("Tip_AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to create a new session. Others can join using your &apos;Me&apos; address ähnelt.
        /// </summary>
        internal static string Tip_ButtonCreate {
            get {
                return ResourceManager.GetString("Tip_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the maximum distance at which aircraft will be injected into the simulator ähnelt.
        /// </summary>
        internal static string Tip_CircleOfActivity {
            get {
                return ResourceManager.GetString("Tip_CircleOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install the required Microsoft C++ module for the X-Plane plugin ähnelt.
        /// </summary>
        internal static string Tip_CPP {
            get {
                return ResourceManager.GetString("Tip_CPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Receive early notification to try a new version before it is offically released. ähnelt.
        /// </summary>
        internal static string Tip_EarlyUpdate {
            get {
                return ResourceManager.GetString("Tip_EarlyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically adjust other aircraft to compensate for differences in scenery airport elevation ähnelt.
        /// </summary>
        internal static string Tip_Elevation {
            get {
                return ResourceManager.GetString("Tip_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length of the recording stored in the recorder ähnelt.
        /// </summary>
        internal static string Tip_EndTime {
            get {
                return ResourceManager.GetString("Tip_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update the file &apos;euroscope.txt&apos; with current aircraft data for showing in Euroscope ähnelt.
        /// </summary>
        internal static string Tip_Euroscope {
            get {
                return ResourceManager.GetString("Tip_Euroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the distance you want your aircraft to be moved behind another aircraft. See View|Aircraft, &apos;Follow&apos; option ähnelt.
        /// </summary>
        internal static string Tip_Follow {
            get {
                return ResourceManager.GetString("Tip_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The radio frequency you are controlling on ähnelt.
        /// </summary>
        internal static string Tip_Frequency {
            get {
                return ResourceManager.GetString("Tip_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to join the global public session ähnelt.
        /// </summary>
        internal static string Tip_GlobalButton {
            get {
                return ResourceManager.GetString("Tip_GlobalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically join the global public session when JoinFS starts ähnelt.
        /// </summary>
        internal static string Tip_GlobalJoin {
            get {
                return ResourceManager.GetString("Tip_GlobalJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A short description for this hub that will appear in everyone&apos;s hub list ähnelt.
        /// </summary>
        internal static string Tip_HubAbout {
            get {
                return ResourceManager.GetString("Tip_HubAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional domain name address, for example, &apos;myserver.com&apos; ähnelt.
        /// </summary>
        internal static string Tip_HubDomain {
            get {
                return ResourceManager.GetString("Tip_HubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional information about upcoming events or meeting dates and times ähnelt.
        /// </summary>
        internal static string Tip_HubEvent {
            get {
                return ResourceManager.GetString("Tip_HubEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a public session that will appear in everyone&apos;s hub list. Port Forwarding required. See manual. ähnelt.
        /// </summary>
        internal static string Tip_HubMode {
            get {
                return ResourceManager.GetString("Tip_HubMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The public name of this hub that will be shown in everyone&apos;s hub list ähnelt.
        /// </summary>
        internal static string Tip_HubName {
            get {
                return ResourceManager.GetString("Tip_HubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details of a voice server associated with this hub. For example, &quot;ts3.myserver.com&quot; ähnelt.
        /// </summary>
        internal static string Tip_HubVoice {
            get {
                return ResourceManager.GetString("Tip_HubVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the colour to use when something in JoinFS is inactive or failed ähnelt.
        /// </summary>
        internal static string Tip_Inactive {
            get {
                return ResourceManager.GetString("Tip_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the address of a session and click &apos;Join&apos; ähnelt.
        /// </summary>
        internal static string Tip_Join {
            get {
                return ResourceManager.GetString("Tip_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to join the session at the given address ähnelt.
        /// </summary>
        internal static string Tip_JoinButton {
            get {
                return ResourceManager.GetString("Tip_JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The colour of the labels of injected aircraft in the simulator ähnelt.
        /// </summary>
        internal static string Tip_LabelColour {
            get {
                return ResourceManager.GetString("Tip_LabelColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ATC level at which you are controlling ähnelt.
        /// </summary>
        internal static string Tip_Level {
            get {
                return ResourceManager.GetString("Tip_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify which UDP network port JoinFS will use - default is 6112 ähnelt.
        /// </summary>
        internal static string Tip_LocalPort {
            get {
                return ResourceManager.GetString("Tip_LocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep looping back to the start of the recording during play back. ähnelt.
        /// </summary>
        internal static string Tip_Loop {
            get {
                return ResourceManager.GetString("Tip_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reduce the amount of network data used by JoinFS - may affect performance ähnelt.
        /// </summary>
        internal static string Tip_LowBandwidth {
            get {
                return ResourceManager.GetString("Tip_LowBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is your address. Others can join you using this address ähnelt.
        /// </summary>
        internal static string Tip_Me {
            get {
                return ResourceManager.GetString("Tip_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically scan for models every time JoinFS connects to the flight simulator ähnelt.
        /// </summary>
        internal static string Tip_ModelScan {
            get {
                return ResourceManager.GetString("Tip_ModelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow this client to receive more than one aircraft from any other client in a session. ähnelt.
        /// </summary>
        internal static string Tip_MultiObjects {
            get {
                return ResourceManager.GetString("Tip_MultiObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join/leave the session at the given address ähnelt.
        /// </summary>
        internal static string Tip_NetworkButton {
            get {
                return ResourceManager.GetString("Tip_NetworkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a personal name for others to see in JoinFS ähnelt.
        /// </summary>
        internal static string Tip_Nickname {
            get {
                return ResourceManager.GetString("Tip_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start recording the selected aircraft and add them to the existing aircraft already stored in the recorder. Existing aircraft will be also be played back in the simulator during overdub ähnelt.
        /// </summary>
        internal static string Tip_Overdub {
            get {
                return ResourceManager.GetString("Tip_Overdub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protect your session with a password ähnelt.
        /// </summary>
        internal static string Tip_Password {
            get {
                return ResourceManager.GetString("Tip_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play/pause the aircraft stored in the recorder ähnelt.
        /// </summary>
        internal static string Tip_Play {
            get {
                return ResourceManager.GetString("Tip_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install the required plugin for X-Plane ähnelt.
        /// </summary>
        internal static string Tip_Plugin {
            get {
                return ResourceManager.GetString("Tip_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the IP address of the machine running X-Plane. Leave blank if on the same machine ähnelt.
        /// </summary>
        internal static string Tip_PluginAddress {
            get {
                return ResourceManager.GetString("Tip_PluginAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current position in the recording. Drag the bar to move forwards and backwards in the recording ähnelt.
        /// </summary>
        internal static string Tip_Position {
            get {
                return ResourceManager.GetString("Tip_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start recording the selected aircraft ähnelt.
        /// </summary>
        internal static string Tip_Record {
            get {
                return ResourceManager.GetString("Tip_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the aircraft altitude as part of the aircraft label ähnelt.
        /// </summary>
        internal static string Tip_ShowAltitude {
            get {
                return ResourceManager.GetString("Tip_ShowAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the aircraft callsign as part of the aircraft label ähnelt.
        /// </summary>
        internal static string Tip_ShowCallsign {
            get {
                return ResourceManager.GetString("Tip_ShowCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the aircraft distance as part of the aircraft label ähnelt.
        /// </summary>
        internal static string Tip_ShowDistance {
            get {
                return ResourceManager.GetString("Tip_ShowDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the pilot&apos;s nickname as part of the aircraft label ähnelt.
        /// </summary>
        internal static string Tip_ShowNickname {
            get {
                return ResourceManager.GetString("Tip_ShowNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show nicknames instead of callsigns in the simulator ähnelt.
        /// </summary>
        internal static string Tip_ShowNicknames {
            get {
                return ResourceManager.GetString("Tip_ShowNicknames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the aircraft speed as part of the aircraft label ähnelt.
        /// </summary>
        internal static string Tip_ShowSpeed {
            get {
                return ResourceManager.GetString("Tip_ShowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect/disconnect the flight simulator ähnelt.
        /// </summary>
        internal static string Tip_SimulatorButton {
            get {
                return ResourceManager.GetString("Tip_SimulatorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die version | open map | total hub users, session users | contribute ähnelt.
        /// </summary>
        internal static string Tip_Status {
            get {
                return ResourceManager.GetString("Tip_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop recording/playing the aircraft ähnelt.
        /// </summary>
        internal static string Tip_Stop {
            get {
                return ResourceManager.GetString("Tip_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable TCAS in X-Plane to allow map support. Aircraft will be acquired by the plugin which may interfere with other plugins. ähnelt.
        /// </summary>
        internal static string Tip_TCAS {
            get {
                return ResourceManager.GetString("Tip_TCAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time since recording/playback started ähnelt.
        /// </summary>
        internal static string Tip_Time {
            get {
                return ResourceManager.GetString("Tip_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show help when mouse pointer is over window items ähnelt.
        /// </summary>
        internal static string Tip_ToolTips {
            get {
                return ResourceManager.GetString("Tip_ToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically broadcast VRS TACPAC objects ähnelt.
        /// </summary>
        internal static string Tip_VRS {
            get {
                return ResourceManager.GetString("Tip_VRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the colour to use when something in JoinFS is waiting to become active ähnelt.
        /// </summary>
        internal static string Tip_Waiting {
            get {
                return ResourceManager.GetString("Tip_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update the file &apos;whazzup.txt&apos; with aircraft data to use in your own online maps ähnelt.
        /// </summary>
        internal static string Tip_Whazzup {
            get {
                return ResourceManager.GetString("Tip_Whazzup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include all AI aircraft in the &apos;whazzup.txt&apos; file ähnelt.
        /// </summary>
        internal static string Tip_WhazzupAI {
            get {
                return ResourceManager.GetString("Tip_WhazzupAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include aircraft from all public hubs in the &apos;whazzup.txt&apos; file ähnelt.
        /// </summary>
        internal static string Tip_WhazzupGlobal {
            get {
                return ResourceManager.GetString("Tip_WhazzupGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable connection to the X-Plane flight simulator ähnelt.
        /// </summary>
        internal static string Tip_Xplane {
            get {
                return ResourceManager.GetString("Tip_Xplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TwinProp ähnelt.
        /// </summary>
        internal static string TwinProp {
            get {
                return ResourceManager.GetString("TwinProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved Recording ähnelt.
        /// </summary>
        internal static string UnsavedRecording {
            get {
                return ResourceManager.GetString("UnsavedRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify Password ähnelt.
        /// </summary>
        internal static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice ähnelt.
        /// </summary>
        internal static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only get weather observations from an aircraft on the network. ähnelt.
        /// </summary>
        internal static string WeatherObservation {
            get {
                return ResourceManager.GetString("WeatherObservation", resourceCulture);
            }
        }
    }
}
